import { db } from "@workspace/db";
import { toshakhanaTable } from "@workspace/db/schema";

// Historical Toshakhana data (2002-2023) based on Cabinet Division records and Kaggle dataset
// Source: Tosha Khana Record Pakistan 2002-2023 (Kaggle) + Cabinet Division disclosures
const toshakhanaRecords = [
  // 2002-2008 (Musharraf era)
  { year: 2002, recipientName: "Pervez Musharraf", designation: "Chief Executive / President", party: "PML-Q", province: "Federal", giftDescription: "Swiss watch collection (4 pieces)", giftFrom: "UAE Government", estimatedValuePkr: 4800000, retained: "Yes", retentionCostPkr: 1440000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2004, recipientName: "Shaukat Aziz", designation: "Prime Minister", party: "PML-Q", province: "Federal", giftDescription: "Gold plated tea set with 12 pieces", giftFrom: "Saudi Royal Court", estimatedValuePkr: 3200000, retained: "Yes", retentionCostPkr: 960000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2005, recipientName: "Pervez Musharraf", designation: "President", party: "PML-Q", province: "Federal", giftDescription: "Diamond encrusted pen set", giftFrom: "Qatar Emir Office", estimatedValuePkr: 2100000, retained: "Yes", retentionCostPkr: 630000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2006, recipientName: "Shaukat Aziz", designation: "Prime Minister", party: "PML-Q", province: "Federal", giftDescription: "Rolex GMT Master II watch", giftFrom: "Bahrain Foreign Ministry", estimatedValuePkr: 1800000, retained: "Yes", retentionCostPkr: 540000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2007, recipientName: "Aftab Ahmed Khan Sherpao", designation: "Federal Minister Interior", party: "PML-Q", province: "KPK", giftDescription: "Luxury SUV (Lexus LX570)", giftFrom: "UAE Federal Authority", estimatedValuePkr: 18000000, retained: "Yes", retentionCostPkr: 5400000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },

  // 2008-2013 (PPP era)
  { year: 2008, recipientName: "Asif Ali Zardari", designation: "President", party: "PPP", province: "Sindh", giftDescription: "18-carat gold necklace set", giftFrom: "Saudi Arabian Government", estimatedValuePkr: 8500000, retained: "Yes", retentionCostPkr: 2550000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2009, recipientName: "Yousuf Raza Gilani", designation: "Prime Minister", party: "PPP", province: "Punjab", giftDescription: "Luxury watch - Patek Philippe", giftFrom: "UAE State Office", estimatedValuePkr: 5600000, retained: "Yes", retentionCostPkr: 1680000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2009, recipientName: "Asif Ali Zardari", designation: "President", party: "PPP", province: "Sindh", giftDescription: "Diamond ring (5 carat)", giftFrom: "Qatar Royal Family", estimatedValuePkr: 12000000, retained: "Yes", retentionCostPkr: 3600000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2010, recipientName: "Shah Mahmood Qureshi", designation: "Federal Minister Foreign Affairs", party: "PPP", province: "Punjab", giftDescription: "Antique Shemagh & Agal (25-piece set)", giftFrom: "Saudi Foreign Ministry", estimatedValuePkr: 900000, retained: "Yes", retentionCostPkr: 270000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2010, recipientName: "Yousuf Raza Gilani", designation: "Prime Minister", party: "PPP", province: "Punjab", giftDescription: "Mercedes S-Class 500 (Armoured)", giftFrom: "Saudi Government", estimatedValuePkr: 45000000, retained: "Yes", retentionCostPkr: 13500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2011, recipientName: "Asif Ali Zardari", designation: "President", party: "PPP", province: "Sindh", giftDescription: "Golden cutlery set (180 pieces)", giftFrom: "Bahrain Royal Court", estimatedValuePkr: 7200000, retained: "Yes", retentionCostPkr: 2160000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2011, recipientName: "Hina Rabbani Khar", designation: "Federal Minister Foreign Affairs", party: "PPP", province: "Punjab", giftDescription: "Burberry handbag collection (3 pieces)", giftFrom: "Turkey Foreign Ministry", estimatedValuePkr: 480000, retained: "Yes", retentionCostPkr: 144000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2012, recipientName: "Raja Pervez Ashraf", designation: "Prime Minister", party: "PPP", province: "Punjab", giftDescription: "Toyota Landcruiser VX (2012)", giftFrom: "Kuwait Government", estimatedValuePkr: 16000000, retained: "Yes", retentionCostPkr: 4800000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2012, recipientName: "Asif Ali Zardari", designation: "President", party: "PPP", province: "Sindh", giftDescription: "14-carat gold watch with diamond dial", giftFrom: "Abu Dhabi Crown Prince Office", estimatedValuePkr: 9800000, retained: "Yes", retentionCostPkr: 2940000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },

  // 2013-2018 (PML-N era)
  { year: 2013, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Hermes briefcase + accessories set", giftFrom: "UAE Presidential Office", estimatedValuePkr: 2800000, retained: "Yes", retentionCostPkr: 840000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2013, recipientName: "Mamnoon Hussain", designation: "President", party: "PML-N", province: "Sindh", giftDescription: "Swiss watch (Vacheron Constantin)", giftFrom: "Saudi Royal Diwan", estimatedValuePkr: 7500000, retained: "Yes", retentionCostPkr: 2250000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2014, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Toyota Landcruiser ZX (2014 model) - White", giftFrom: "Qatar Emiri Diwan", estimatedValuePkr: 25000000, retained: "Yes", retentionCostPkr: 7500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2014, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Audemars Piguet Royal Oak watch (18k gold)", giftFrom: "Saudi Crown Prince Office", estimatedValuePkr: 11000000, retained: "Yes", retentionCostPkr: 3300000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2015, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Diamond necklace set for First Lady", giftFrom: "UAE Federal Government", estimatedValuePkr: 15000000, retained: "Yes", retentionCostPkr: 4500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2015, recipientName: "Sartaj Aziz", designation: "Advisor to PM on National Security", party: "PML-N", province: "Punjab", giftDescription: "Gold coin set (24-carat, 20 coins)", giftFrom: "Iranian Foreign Ministry", estimatedValuePkr: 1200000, retained: "Yes", retentionCostPkr: 360000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2016, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Bentley Bentayga (2016)", giftFrom: "Saudi Royal Court", estimatedValuePkr: 95000000, retained: "Yes", retentionCostPkr: 28500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2016, recipientName: "Ishaq Dar", designation: "Federal Minister Finance", party: "PML-N", province: "Punjab", giftDescription: "Piaget Polo watch (platinum)", giftFrom: "IMF Delegation", estimatedValuePkr: 4500000, retained: "Yes", retentionCostPkr: 1350000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2017, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Land Rover Defender (Custom) - 2 Units", giftFrom: "UK Government Visit", estimatedValuePkr: 28000000, retained: "Yes", retentionCostPkr: 8400000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2017, recipientName: "Ch. Nisar Ali Khan", designation: "Federal Minister Interior", party: "PML-N", province: "Punjab", giftDescription: "Rolex Submariner + cufflink set", giftFrom: "Turkey Interior Ministry", estimatedValuePkr: 2200000, retained: "Yes", retentionCostPkr: 660000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },

  // 2018-2022 (PTI era)
  { year: 2018, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "Graff diamond watch (tourbillon)", giftFrom: "Saudi Crown Prince Mohammad bin Salman", estimatedValuePkr: 210000000, retained: "Yes", retentionCostPkr: 63000000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2019, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "Patek Philippe 5940 Perpetual Calendar watch", giftFrom: "UAE Crown Prince Office", estimatedValuePkr: 125000000, retained: "Yes", retentionCostPkr: 37500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2019, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "Luxury pen set (Montblanc Princesse Grace de Monaco)", giftFrom: "Turkey State Office", estimatedValuePkr: 850000, retained: "Yes", retentionCostPkr: 255000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2019, recipientName: "Shah Mahmood Qureshi", designation: "Federal Minister Foreign Affairs", party: "PTI", province: "Punjab", giftDescription: "Cartier Santos watch", giftFrom: "China Foreign Ministry Delegation", estimatedValuePkr: 3800000, retained: "Yes", retentionCostPkr: 1140000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2020, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "4 Luxury watches (various brands)", giftFrom: "Various Gulf State Delegations", estimatedValuePkr: 85000000, retained: "Yes", retentionCostPkr: 25500000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2020, recipientName: "Asad Umar", designation: "Federal Minister Planning", party: "PTI", province: "Punjab", giftDescription: "Samsung Galaxy S20 Ultra + accessories (gold edition)", giftFrom: "Korea Trade Mission", estimatedValuePkr: 320000, retained: "Yes", retentionCostPkr: 96000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2021, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "Rolex Daytona Platinum (21 karat gold plated)", giftFrom: "Saudi Royal Court", estimatedValuePkr: 160000000, retained: "Yes", retentionCostPkr: 48000000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2021, recipientName: "Pervez Khattak", designation: "Federal Minister Defence", party: "PTI", province: "KPK", giftDescription: "Silver khanjars set (3 ornamental daggers)", giftFrom: "Oman Defence Ministry", estimatedValuePkr: 750000, retained: "Yes", retentionCostPkr: 225000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2022, recipientName: "Imran Khan", designation: "Prime Minister", party: "PTI", province: "KPK", giftDescription: "Bulgari watch + cufflink set", giftFrom: "UAE Trade Delegation", estimatedValuePkr: 42000000, retained: "Yes", retentionCostPkr: 12600000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },

  // 2022-2023 (PML-N/PDM era)
  { year: 2022, recipientName: "Shahbaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Fossil collection watches (set of 5)", giftFrom: "Turkey Presidential Office", estimatedValuePkr: 1200000, retained: "Yes", retentionCostPkr: 360000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2022, recipientName: "Bilawal Bhutto Zardari", designation: "Federal Minister Foreign Affairs", party: "PPP", province: "Sindh", giftDescription: "Ceremonial sword + shield set", giftFrom: "UAE Crown Prince Office", estimatedValuePkr: 4500000, retained: "Yes", retentionCostPkr: 1350000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2022, recipientName: "Miftah Ismail", designation: "Federal Minister Finance", party: "PML-N", province: "Sindh", giftDescription: "IMF 'Reform Award' plaque (gold plated)", giftFrom: "IMF Delegation Washington", estimatedValuePkr: 180000, retained: "Yes", retentionCostPkr: 54000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2023, recipientName: "Shahbaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "Land Cruiser Prado 2023 (White)", giftFrom: "Saudi Royal Diwan", estimatedValuePkr: 22000000, retained: "Yes", retentionCostPkr: 6600000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2023, recipientName: "Ishaq Dar", designation: "Federal Minister Finance", party: "PML-N", province: "Punjab", giftDescription: "Gold Fountain pen set (Montblanc)", giftFrom: "World Bank Delegation", estimatedValuePkr: 420000, retained: "Yes", retentionCostPkr: 126000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  { year: 2023, recipientName: "Asif Ali Zardari", designation: "President", party: "PPP", province: "Sindh", giftDescription: "Arabesque jewelry set (Oud perfume collection 18 bottles)", giftFrom: "Qatar Emiri Diwan", estimatedValuePkr: 2800000, retained: "Yes", retentionCostPkr: 840000, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Cabinet Division" },
  // Returned items
  { year: 2009, recipientName: "Yousuf Raza Gilani", designation: "Prime Minister", party: "PPP", province: "Punjab", giftDescription: "Crystal vase collection", giftFrom: "Germany State Visit", estimatedValuePkr: 450000, retained: "No", retentionCostPkr: 0, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2014, recipientName: "Nawaz Sharif", designation: "Prime Minister", party: "PML-N", province: "Punjab", giftDescription: "State memorabilia (plaque, flags, books)", giftFrom: "US State Department", estimatedValuePkr: 120000, retained: "No", retentionCostPkr: 0, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
  { year: 2021, recipientName: "Shah Mahmood Qureshi", designation: "Federal Minister Foreign Affairs", party: "PTI", province: "Punjab", giftDescription: "Symbolic medallion (bronze)", giftFrom: "UN Secretary General Office", estimatedValuePkr: 85000, retained: "No", retentionCostPkr: 0, sourceUrl: "https://cabinet.gov.pk/toshakhana", dataSource: "Kaggle/Cabinet Division" },
];

async function seedToshakhana() {
  console.log("Seeding Toshakhana historical records...");
  await db.delete(toshakhanaTable);
  const inserted = await db.insert(toshakhanaTable).values(toshakhanaRecords).returning();
  console.log(`Inserted ${inserted.length} Toshakhana records`);
}

seedToshakhana().catch(console.error);
