import { db } from "@workspace/db";
import { publicDatabasesTable, officialsTable, alertsTable } from "@workspace/db/schema";

async function seed() {
  console.log("Seeding Pakistan Accountability Intelligence System...");

  await db.delete(alertsTable);
  await db.delete(officialsTable);
  await db.delete(publicDatabasesTable);

  const databases = [
    {
      name: "National Database and Registration Authority",
      acronym: "NADRA",
      category: "electoral",
      organization: "Ministry of Interior",
      description: "Central identity database containing CNIC (Computerized National Identity Card) records for all Pakistani citizens. The backbone for cross-referencing individuals across all other government databases.",
      dataTypes: JSON.stringify(["CNIC numbers", "Biometric data", "Family tree data", "Address history", "Date of birth"]),
      accessLevel: "restricted",
      url: "https://nadra.gov.pk",
      recordsEstimated: "130 million+",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["CNIC", "name", "father_name", "date_of_birth", "address"]),
      notes: "CNIC is the master key linking individuals across all government systems. Partial access via verification API for authorized agencies.",
    },
    {
      name: "Election Commission of Pakistan - Asset Declarations",
      acronym: "ECP",
      category: "electoral",
      organization: "Election Commission of Pakistan",
      description: "Mandatory asset and financial declarations filed by all candidates and elected officials. Publicly accessible via the ECP website. Key source for wealth anomaly detection.",
      dataTypes: JSON.stringify(["Asset declarations", "Tax returns", "Business interests", "Liabilities", "Income sources"]),
      accessLevel: "public",
      url: "https://ecp.gov.pk",
      recordsEstimated: "20,000+ declarations",
      lastUpdated: "2024-02",
      integrationStatus: "integrated",
      keyFields: JSON.stringify(["CNIC", "name", "party", "constituency", "declared_assets", "declared_liabilities"]),
      notes: "Fully public and downloadable. Critical for asset mismatch detection. PDF format requires OCR/parsing.",
    },
    {
      name: "Securities and Exchange Commission of Pakistan - Company Registry",
      acronym: "SECP",
      category: "corporate",
      organization: "Securities and Exchange Commission of Pakistan",
      description: "Official registry of all incorporated companies in Pakistan. Contains director/shareholder information linkable to CNIC. Essential for detecting shell companies and beneficial ownership.",
      dataTypes: JSON.stringify(["Company registrations", "Director/shareholder info", "Share structures", "Annual returns", "CNIC of directors"]),
      accessLevel: "public",
      url: "https://efiling.secp.gov.pk",
      recordsEstimated: "200,000+ companies",
      lastUpdated: "2024-01",
      integrationStatus: "integrated",
      keyFields: JSON.stringify(["company_number", "director_cnic", "shareholder_cnic", "registered_address", "paid_up_capital"]),
      notes: "Public eFiling portal available. CNIC linkage enables tracing companies to politicians and their relatives.",
    },
    {
      name: "Federal Board of Revenue - Tax Data",
      acronym: "FBR",
      category: "financial",
      organization: "Federal Board of Revenue",
      description: "Tax filing data including income tax returns, business income, and property tax. Restricted access but cross-referenceable with ECP asset declarations to detect unexplained wealth.",
      dataTypes: JSON.stringify(["Income tax returns", "Tax filer status", "Tax paid amounts", "Business income", "Property declarations"]),
      accessLevel: "partial",
      url: "https://fbr.gov.pk",
      recordsEstimated: "4 million+ filers",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["CNIC", "ntn", "income_declared", "tax_paid", "filing_status"]),
      notes: "Active taxpayer list is publicly available. Detailed returns are restricted. FBR-ECP comparison reveals wealth gaps.",
    },
    {
      name: "Public Procurement Regulatory Authority - Contract Database",
      acronym: "PPRA",
      category: "procurement",
      organization: "Public Procurement Regulatory Authority",
      description: "Government procurement contracts, tenders, and awards database. Legally required public disclosure. Enables detection of contract patterns connected to political networks.",
      dataTypes: JSON.stringify(["Contract awards", "Tender notices", "Bidding results", "Vendor information", "Contract values"]),
      accessLevel: "public",
      url: "https://ppra.org.pk",
      recordsEstimated: "500,000+ contracts",
      lastUpdated: "2024-02",
      integrationStatus: "integrated",
      keyFields: JSON.stringify(["contract_id", "procuring_agency", "vendor_name", "vendor_ntn", "contract_value", "award_date"]),
      notes: "Federal PPRA covers federal contracts. Provincial procurement authorities (KPPRA, SPPRA, PPRA Punjab) exist separately.",
    },
    {
      name: "Accountant General Pakistan Revenue - Government Payroll",
      acronym: "AGPR",
      category: "payroll",
      organization: "Ministry of Finance",
      description: "Federal government payroll system covering all civil servants. Critical for ghost employee detection by cross-referencing active CNIC status with NADRA.",
      dataTypes: JSON.stringify(["Employee names", "CNIC", "Salary grades", "Departments", "Posting history"]),
      accessLevel: "restricted",
      url: "https://agpr.gov.pk",
      recordsEstimated: "600,000+ federal employees",
      lastUpdated: "2023-12",
      integrationStatus: "planned",
      keyFields: JSON.stringify(["employee_cnic", "department", "basic_pay_scale", "posting_date", "current_posting"]),
      notes: "Ghost employee detection requires NADRA + AGPR cross-reference. Provincial payrolls managed by respective AGs.",
    },
    {
      name: "National Accountability Bureau - Conviction & Case Records",
      acronym: "NAB",
      category: "judicial",
      organization: "National Accountability Bureau",
      description: "Records of accountability cases, convictions, plea bargains, and investigated entities. Public accountability court decisions are published and searchable.",
      dataTypes: JSON.stringify(["Case files", "Convictions", "Plea bargains", "Assets recovered", "Accused names"]),
      accessLevel: "partial",
      url: "https://nab.gov.pk",
      recordsEstimated: "10,000+ cases",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["accused_name", "case_number", "amount_involved", "verdict", "reference_date"]),
      notes: "Accountability court verdicts are public. NAB uses CNIC for identification in cases.",
    },
    {
      name: "Pakistan Revenue Automation Limited - Land Records",
      acronym: "PRAL",
      category: "land",
      organization: "Provincial Revenue Departments",
      description: "Digitized land ownership records (Fard) for Punjab, KPK, Sindh, and Balochistan. Enables detection of undisclosed property assets held by officials or relatives.",
      dataTypes: JSON.stringify(["Land ownership", "Property transfers", "Khasra numbers", "Owner CNIC", "Survey data"]),
      accessLevel: "partial",
      url: "https://punjab-zameen.gov.pk",
      recordsEstimated: "50 million+ land records",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["owner_cnic", "khasra_number", "district", "land_area", "transfer_date"]),
      notes: "Punjab most digitized. Sindh, KPK, Balochistan partially digitized. Key for finding undisclosed land assets.",
    },
    {
      name: "State Bank of Pakistan - Financial Sanctions List",
      acronym: "SBP",
      category: "financial",
      organization: "State Bank of Pakistan",
      description: "Financial sanctions, AML/CFT watchlists, and Politically Exposed Persons (PEP) database. Includes FATF compliance data and suspicious transaction monitoring.",
      dataTypes: JSON.stringify(["Sanctions lists", "PEP database", "Suspicious transaction reports", "AML flags", "Shell company alerts"]),
      accessLevel: "partial",
      url: "https://sbp.org.pk",
      recordsEstimated: "Classified",
      lastUpdated: "2024-02",
      integrationStatus: "planned",
      keyFields: JSON.stringify(["name", "cnic", "account_details", "pep_status", "sanction_reason"]),
      notes: "PEP list and sanctions data partially public. SBP reports suspicious transactions to FMU (Financial Monitoring Unit).",
    },
    {
      name: "Pakistan Tehsil Municipal Administration - Property Tax",
      acronym: "TMA",
      category: "land",
      organization: "Local Government Departments",
      description: "Municipal property tax records including commercial and residential properties. Useful for detecting undeclared urban properties linked to politicians via relatives.",
      dataTypes: JSON.stringify(["Property ownership", "Tax assessments", "Commercial property", "Residential property", "CNIC of owners"]),
      accessLevel: "partial",
      url: null,
      recordsEstimated: "25 million+ properties",
      lastUpdated: "2023-09",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["owner_name", "owner_cnic", "property_address", "assessed_value", "tax_paid"]),
      notes: "Digitization inconsistent across tehsils. Urban properties better covered. Critical for detecting hidden real estate.",
    },
    {
      name: "Overseas Employment Corporation - Remittance Data",
      acronym: "OEC",
      category: "financial",
      organization: "Ministry of Overseas Pakistanis",
      description: "Data on overseas Pakistanis and formal remittance channels. Helps trace foreign income flows and detect money laundering through remittance accounts.",
      dataTypes: JSON.stringify(["Worker registrations", "Remittance amounts", "Country of employment", "Bank accounts", "Family CNIC"]),
      accessLevel: "restricted",
      url: "https://oec.org.pk",
      recordsEstimated: "9 million+ overseas workers",
      lastUpdated: "2023-11",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["worker_cnic", "destination_country", "remittance_amount", "frequency", "bank_account"]),
      notes: "Useful for reverse money laundering detection — large inbound remittances to political families.",
    },
    {
      name: "Competition Commission of Pakistan - Merger & Acquisition Records",
      acronym: "CCP",
      category: "corporate",
      organization: "Competition Commission of Pakistan",
      description: "Records of mergers, acquisitions, and anti-competitive practices. Reveals when politically connected companies gain market dominance through regulatory capture.",
      dataTypes: JSON.stringify(["Merger approvals", "Market share data", "Cartel investigations", "Company ownership", "Board compositions"]),
      accessLevel: "public",
      url: "https://cc.gov.pk",
      recordsEstimated: "5,000+ decisions",
      lastUpdated: "2024-01",
      integrationStatus: "planned",
      keyFields: JSON.stringify(["company_name", "transaction_value", "market_share_post", "approval_date", "board_members"]),
      notes: "CCP decisions are publicly published. Useful for detecting regulatory capture by politically connected companies.",
    },
    {
      name: "Federal Investigation Agency - Proclaimed Offenders",
      acronym: "FIA",
      category: "law_enforcement",
      organization: "Federal Investigation Agency",
      description: "FIA cybercrime, financial crime, and human trafficking case records. Includes IBOS (Immigration Border Operations System) exit/entry data for tracking asset movement.",
      dataTypes: JSON.stringify(["Case records", "Proclaimed offenders", "Immigration data", "Cybercrime reports", "Hawala busts"]),
      accessLevel: "partial",
      url: "https://fia.gov.pk",
      recordsEstimated: "Classified",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["accused_cnic", "case_type", "offense", "status", "travel_history"]),
      notes: "Publicly wanted lists available. Immigration data critical for tracking offshore asset movement.",
    },
    {
      name: "Development Authorities Budget Tracker - PSDP",
      acronym: "PSDP",
      category: "procurement",
      organization: "Planning Commission of Pakistan",
      description: "Public Sector Development Programme tracking all federal development projects, funds released, and expenditure. Enables detection of fund diversion at district level.",
      dataTypes: JSON.stringify(["Development projects", "Funds released", "Expenditure", "Implementing agencies", "District allocations"]),
      accessLevel: "public",
      url: "https://pc.gov.pk",
      recordsEstimated: "10,000+ active projects",
      lastUpdated: "2024-02",
      integrationStatus: "integrated",
      keyFields: JSON.stringify(["project_id", "district", "approved_cost", "released_amount", "expenditure", "status"]),
      notes: "Fully public PSDP data. Cross-referencing fund releases vs. contracts awarded reveals suspicious patterns.",
    },
    {
      name: "Directorate General of Immigration - Passport & Travel",
      acronym: "DGI",
      category: "financial",
      organization: "Ministry of Interior",
      description: "Passport issuance and travel history records. Useful for tracking when officials travel to offshore financial centers and correlating with suspicious fund movements.",
      dataTypes: JSON.stringify(["Passport records", "Travel history", "Entry/exit stamps", "Visa data", "Dual nationality flags"]),
      accessLevel: "restricted",
      url: "https://dgip.gov.pk",
      recordsEstimated: "25 million+ passports",
      lastUpdated: "2024-01",
      integrationStatus: "manual",
      keyFields: JSON.stringify(["passport_number", "cnic", "travel_dates", "destination", "dual_nationality"]),
      notes: "Restricted access. Travel to UAE, UK, Switzerland by politicians during asset declaration periods is flagged.",
    },
  ];

  const insertedDbs = await db.insert(publicDatabasesTable).values(databases).returning();
  console.log(`Inserted ${insertedDbs.length} database records`);

  const buildConnections = (name: string, id: number, companies: string[], relatives: string[], districts: string[]) => {
    const nodes: Array<{ id: string; label: string; type: string; riskScore?: number; value?: string }> = [
      { id: `official-${id}`, label: name, type: "official", riskScore: 0 },
    ];
    const edges: Array<{ source: string; target: string; label: string; suspicious: boolean }> = [];

    companies.forEach((c, i) => {
      nodes.push({ id: `company-${id}-${i}`, label: c, type: "company", value: `PKR ${(Math.random() * 500 + 50).toFixed(0)}M` });
      edges.push({ source: `official-${id}`, target: `company-${id}-${i}`, label: "Director", suspicious: i === 0 });
    });

    relatives.forEach((r, i) => {
      nodes.push({ id: `relative-${id}-${i}`, label: r, type: "relative" });
      edges.push({ source: `official-${id}`, target: `relative-${id}-${i}`, label: "Relative", suspicious: false });
      if (companies[i]) {
        nodes.push({ id: `contract-${id}-${i}`, label: `Contract #PK-${id}${i}`, type: "contract", value: `PKR ${(Math.random() * 200 + 20).toFixed(0)}M` });
        edges.push({ source: `relative-${id}-${i}`, target: `company-${id}-${i}`, label: "Shareholder", suspicious: true });
        edges.push({ source: `company-${id}-${i}`, target: `contract-${id}-${i}`, label: "Won Contract", suspicious: true });
      }
    });

    districts.forEach((d, i) => {
      nodes.push({ id: `district-${id}-${i}`, label: d, type: "district" });
      edges.push({ source: `official-${id}`, target: `district-${id}-${i}`, label: "Directed Funds", suspicious: true });
    });

    return { nodes, edges };
  };

  const officials = [
    {
      name: "Malik Asghar Hussain",
      cnicPartial: "35202-XXXXX-1",
      position: "MNA - National Assembly",
      party: "PML-N",
      province: "Punjab",
      constituency: "NA-73 Sialkot",
      riskScore: 87.4,
      riskTrend: "rising",
      flagCount: 14,
      assetsDeclared: "PKR 320 Million",
      lastUpdated: "2024-02-15",
      companiesJson: JSON.stringify([
        { companyName: "Hussain Steel Mills Pvt Ltd", secp_number: "SECP-0047823", relationship: "Director", directorship: true, contractsValue: "PKR 847M" },
        { companyName: "Al-Hussain Construction Co.", secp_number: "SECP-0092341", relationship: "Beneficial Owner via spouse", directorship: false, contractsValue: "PKR 234M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "PPRA-2023-0472", projectName: "Sialkot Bypass Road Phase II", amount: "PKR 1.2B", awardedTo: "Hussain Steel Mills Pvt Ltd", connection: "Direct company ownership", year: 2023, source: "PPRA" },
        { contractId: "PPRA-2022-1891", projectName: "Rural Water Supply Scheme Daska", amount: "PKR 340M", awardedTo: "Al-Hussain Construction Co.", connection: "Spouse is director", year: 2022, source: "PPRA" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Asma Hussain (Wife)", relationship: "Spouse", companies: ["Al-Hussain Construction Co."], contracts: 3 },
        { name: "Usman Hussain (Brother)", relationship: "Sibling", companies: ["Hussain Steel Mills Pvt Ltd", "GreenPak Agro"], contracts: 5 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Sialkot", amount: "PKR 3.4B", year: 2023, contractsBack: 7, suspiciousLinks: true },
        { district: "Gujranwala", amount: "PKR 1.8B", year: 2022, contractsBack: 3, suspiciousLinks: true },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Circular contracting via relatives", weight: 28.5, description: "Spouse and brother received contracts in districts where official directed public funds", evidenceLevel: "high" },
        { factor: "Asset-income mismatch (ECP vs FBR)", weight: 22.1, description: "Declared assets PKR 320M vs estimated income PKR 45M over 8 years in politics", evidenceLevel: "high" },
        { factor: "SECP company linked to PPRA contracts", weight: 18.3, description: "Directly owned company received government contracts during tenure", evidenceLevel: "high" },
        { factor: "Undisclosed land holdings", weight: 12.8, description: "Punjab Zameen records show 4 properties not in ECP declaration", evidenceLevel: "medium" },
        { factor: "Relative shell company patterns", weight: 5.7, description: "Brother's company shows minimal operations but multiple contract wins", evidenceLevel: "medium" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Malik Asghar Hussain", 1, ["Hussain Steel Mills", "Al-Hussain Construction"], ["Asma Hussain", "Usman Hussain"], ["Sialkot", "Gujranwala"])),
    },
    {
      name: "Bibi Rubina Akhtar",
      cnicPartial: "44303-XXXXX-2",
      position: "MPA - Sindh Assembly",
      party: "PPP",
      province: "Sindh",
      constituency: "PS-52 Hyderabad",
      riskScore: 79.2,
      riskTrend: "stable",
      flagCount: 11,
      assetsDeclared: "PKR 180 Million",
      lastUpdated: "2024-02-10",
      companiesJson: JSON.stringify([
        { companyName: "Indus Trade International", secp_number: "SECP-0038291", relationship: "Via brother-in-law", directorship: false, contractsValue: "PKR 567M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "SPPRA-2023-0892", projectName: "Hyderabad Drainage System Upgrade", amount: "PKR 890M", awardedTo: "Indus Trade International", connection: "Brother-in-law is director", year: 2023, source: "SPPRA" },
        { contractId: "SPPRA-2022-0341", projectName: "Rural School Construction PS-52", amount: "PKR 230M", awardedTo: "Indus Trade International", connection: "Brother-in-law is director", year: 2022, source: "SPPRA" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Tariq Mehmood (Brother-in-law)", relationship: "In-law", companies: ["Indus Trade International"], contracts: 6 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Hyderabad", amount: "PKR 2.1B", year: 2023, contractsBack: 4, suspiciousLinks: true },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Repeated contract to single relative-linked company", weight: 31.2, description: "Brother-in-law's company won 6 consecutive contracts in her constituency", evidenceLevel: "high" },
        { factor: "Asset declaration anomaly", weight: 20.8, description: "Declared PKR 180M with primary income source listed as farming", evidenceLevel: "high" },
        { factor: "No competitive bidding evidence", weight: 15.4, description: "Contracts awarded via single-source procurement outside SPPRA rules", evidenceLevel: "medium" },
        { factor: "Ghost employee flags in local scheme", weight: 12.8, description: "School construction project had payroll entries for deceased workers", evidenceLevel: "medium" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Bibi Rubina Akhtar", 2, ["Indus Trade International"], ["Tariq Mehmood"], ["Hyderabad"])),
    },
    {
      name: "Fazal ur Rahman Qureshi",
      cnicPartial: "17301-XXXXX-3",
      position: "MNA - National Assembly",
      party: "PTI",
      province: "KPK",
      constituency: "NA-19 Peshawar",
      riskScore: 71.8,
      riskTrend: "rising",
      flagCount: 9,
      assetsDeclared: "PKR 95 Million",
      lastUpdated: "2024-01-28",
      companiesJson: JSON.stringify([
        { companyName: "KPK Construction Consortium", secp_number: "SECP-0071234", relationship: "Son is director", directorship: false, contractsValue: "PKR 412M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "KPPRA-2023-1203", projectName: "Peshawar Ring Road Sub-section 3", amount: "PKR 412M", awardedTo: "KPK Construction Consortium", connection: "Son Bilal Qureshi is director", year: 2023, source: "KPPRA" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Bilal Qureshi (Son)", relationship: "Child", companies: ["KPK Construction Consortium", "Qureshi Logistics Pvt Ltd"], contracts: 4 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Peshawar", amount: "PKR 1.9B", year: 2023, contractsBack: 3, suspiciousLinks: true },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Son's company awarded constituency contracts", weight: 27.4, description: "Son registered company 2 months before father's election, then won major contracts", evidenceLevel: "high" },
        { factor: "SECP registration timing suspicious", weight: 19.6, description: "KPK Construction Consortium registered 58 days before NA-19 election date", evidenceLevel: "high" },
        { factor: "Asset underreporting indicators", weight: 14.8, description: "FBR active taxpayer list shows minimal business income vs. declared assets", evidenceLevel: "medium" },
        { factor: "Single supplier pattern", weight: 10.0, description: "Same company bid and won 4 consecutive KPPRA tenders", evidenceLevel: "low" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Fazal ur Rahman Qureshi", 3, ["KPK Construction Consortium"], ["Bilal Qureshi"], ["Peshawar"])),
    },
    {
      name: "Chaudhry Nawaz Baig",
      cnicPartial: "35401-XXXXX-5",
      position: "Senator",
      party: "PML-N",
      province: "Punjab",
      constituency: "Senate Seat - Punjab",
      riskScore: 65.3,
      riskTrend: "falling",
      flagCount: 7,
      assetsDeclared: "PKR 540 Million",
      lastUpdated: "2024-02-01",
      companiesJson: JSON.stringify([
        { companyName: "Baig Sugar Mills Ltd", secp_number: "SECP-0009871", relationship: "Chairman", directorship: true, contractsValue: "PKR 1.2B" },
        { companyName: "Baig Transport Pvt Ltd", secp_number: "SECP-0043210", relationship: "Director", directorship: true, contractsValue: "PKR 234M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "PPRA-2022-3421", projectName: "Government Sugar Procurement 2022", amount: "PKR 1.2B", awardedTo: "Baig Sugar Mills Ltd", connection: "Direct ownership as chairman", year: 2022, source: "PPRA" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Shahid Baig (Nephew)", relationship: "Nephew", companies: ["Baig Transport Pvt Ltd"], contracts: 2 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Faisalabad", amount: "PKR 890M", year: 2022, contractsBack: 2, suspiciousLinks: false },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Senator voting on sugar sector policy while owning sugar mills", weight: 30.1, description: "Voted on sugar export policy while being chairman of major sugar conglomerate", evidenceLevel: "high" },
        { factor: "Government procurement to owned company", weight: 22.3, description: "Public sugar procurement went to personally owned company without disclosed conflict", evidenceLevel: "high" },
        { factor: "Asset declaration completeness", weight: 12.9, description: "3 offshore business partnerships not disclosed in ECP declaration", evidenceLevel: "medium" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Chaudhry Nawaz Baig", 4, ["Baig Sugar Mills Ltd", "Baig Transport Pvt Ltd"], ["Shahid Baig"], ["Faisalabad"])),
    },
    {
      name: "Sardar Abdul Qayyum Niazi",
      cnicPartial: "38403-XXXXX-9",
      position: "Chief Minister",
      party: "PTI",
      province: "Punjab",
      constituency: "CM Punjab",
      riskScore: 58.7,
      riskTrend: "stable",
      flagCount: 6,
      assetsDeclared: "PKR 210 Million",
      lastUpdated: "2024-02-12",
      companiesJson: JSON.stringify([
        { companyName: "Niazi Agro Farms", secp_number: "SECP-0087654", relationship: "Owner", directorship: true, contractsValue: "PKR 145M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "PPRA-2023-5610", projectName: "Agricultural Subsidy Distribution Punjab", amount: "PKR 145M", awardedTo: "Niazi Agro Farms (indirectly via subsidiary)", connection: "Agricultural subsidy routed through owned farm", year: 2023, source: "Agriculture Dept" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Imtiaz Niazi (Cousin)", relationship: "Cousin", companies: ["Niazi Real Estate", "PakBuild Contractors"], contracts: 3 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Rawalpindi", amount: "PKR 2.4B", year: 2023, contractsBack: 2, suspiciousLinks: false },
        { district: "Lahore", amount: "PKR 3.1B", year: 2023, contractsBack: 1, suspiciousLinks: false },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Agricultural subsidy to self-owned entity", weight: 22.4, description: "Government agricultural subsidies routed through entities with links to CM", evidenceLevel: "medium" },
        { factor: "Cousin company in provincial contracts", weight: 18.9, description: "Cousin's construction company received 3 provincial contracts during CM tenure", evidenceLevel: "medium" },
        { factor: "Land record anomalies", weight: 17.4, description: "Punjab Zameen records show 2 large agricultural plots not in declaration", evidenceLevel: "medium" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Sardar Abdul Qayyum Niazi", 5, ["Niazi Agro Farms"], ["Imtiaz Niazi"], ["Rawalpindi", "Lahore"])),
    },
    {
      name: "Dr. Saima Waqar",
      cnicPartial: "42201-XXXXX-4",
      position: "MNA - National Assembly",
      party: "MQM-P",
      province: "Sindh",
      constituency: "NA-240 Karachi East",
      riskScore: 44.1,
      riskTrend: "stable",
      flagCount: 4,
      assetsDeclared: "PKR 85 Million",
      lastUpdated: "2024-02-08",
      companiesJson: JSON.stringify([
        { companyName: "Waqar Medical Centre Pvt Ltd", secp_number: "SECP-0065432", relationship: "Co-owner with husband", directorship: false, contractsValue: "PKR 23M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "SPPRA-2023-2190", projectName: "Free Medical Camp Services Karachi", amount: "PKR 23M", awardedTo: "Waqar Medical Centre", connection: "Husband co-owns medical center", year: 2023, source: "Sindh Health Dept" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Dr. Imran Waqar (Husband)", relationship: "Spouse", companies: ["Waqar Medical Centre Pvt Ltd"], contracts: 1 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Karachi", amount: "PKR 450M", year: 2023, contractsBack: 1, suspiciousLinks: false },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Minor conflict of interest in healthcare contract", weight: 18.3, description: "Husband's company received small health services contract in her area", evidenceLevel: "low" },
        { factor: "ECP declaration completeness", weight: 15.8, description: "Some investments not fully categorized in financial declaration", evidenceLevel: "low" },
        { factor: "Business linkage transparency", weight: 10.0, description: "Medical center co-ownership not prominently declared in official profile", evidenceLevel: "low" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Dr. Saima Waqar", 6, ["Waqar Medical Centre"], ["Dr. Imran Waqar"], ["Karachi"])),
    },
    {
      name: "Ghulam Mustafa Khar",
      cnicPartial: "32104-XXXXX-7",
      position: "MPA - Punjab Assembly",
      party: "PPP",
      province: "Punjab",
      constituency: "PP-208 Muzaffargarh",
      riskScore: 92.1,
      riskTrend: "rising",
      flagCount: 17,
      assetsDeclared: "PKR 760 Million",
      lastUpdated: "2024-02-18",
      companiesJson: JSON.stringify([
        { companyName: "Khar Petroleum Ltd", secp_number: "SECP-0012903", relationship: "Director", directorship: true, contractsValue: "PKR 2.1B" },
        { companyName: "South Punjab Contractors", secp_number: "SECP-0034521", relationship: "Director via nominee", directorship: false, contractsValue: "PKR 890M" },
        { companyName: "Muzaffargarh Brick Kilns", secp_number: "SECP-0091234", relationship: "Beneficial Owner", directorship: false, contractsValue: "PKR 120M" },
      ]),
      contractsJson: JSON.stringify([
        { contractId: "PPRA-2023-0219", projectName: "South Punjab Motorway Service Areas", amount: "PKR 2.1B", awardedTo: "Khar Petroleum Ltd", connection: "Direct director and major shareholder", year: 2023, source: "NHA/PPRA" },
        { contractId: "PPRA-2022-1567", projectName: "Muzaffargarh District Hospital Expansion", amount: "PKR 890M", awardedTo: "South Punjab Contractors", connection: "Nominee director linked via law firm", year: 2022, source: "PPRA" },
        { contractId: "PPRA-2021-4421", projectName: "Brick Supply for Govt Housing Scheme", amount: "PKR 120M", awardedTo: "Muzaffargarh Brick Kilns", connection: "Beneficial ownership via SECP", year: 2021, source: "Housing Dept" },
      ]),
      relativesJson: JSON.stringify([
        { name: "Ahmad Khar (Son)", relationship: "Child", companies: ["Khar Petroleum Ltd", "Khar Holdings"], contracts: 8 },
        { name: "Zainab Khar (Daughter)", relationship: "Child", companies: ["ZK Imports Pvt Ltd"], contracts: 2 },
        { name: "Mehmood Khar (Brother)", relationship: "Sibling", companies: ["South Punjab Contractors", "Muzaffargarh Brick Kilns"], contracts: 5 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Muzaffargarh", amount: "PKR 4.2B", year: 2023, contractsBack: 9, suspiciousLinks: true },
        { district: "DG Khan", amount: "PKR 2.8B", year: 2022, contractsBack: 5, suspiciousLinks: true },
        { district: "Rajanpur", amount: "PKR 1.1B", year: 2022, contractsBack: 3, suspiciousLinks: true },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Multi-layered circular contracting network", weight: 35.8, description: "Son, daughter, and brother all have companies receiving government contracts in districts he controls funding for", evidenceLevel: "high" },
        { factor: "Extreme asset-income gap", weight: 28.4, description: "Declared PKR 760M in assets vs PKR 67M estimated legitimate income over 15 years", evidenceLevel: "high" },
        { factor: "Nominee director structures (SECP)", weight: 18.9, description: "Uses law firm nominees to obscure directorship in SECP filings", evidenceLevel: "high" },
        { factor: "Cross-district fund diversion", weight: 9.0, description: "Funds allocated to 3 districts all result in contracts to connected entities", evidenceLevel: "high" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Ghulam Mustafa Khar", 7, ["Khar Petroleum Ltd", "South Punjab Contractors", "Muzaffargarh Brick Kilns"], ["Ahmad Khar", "Mehmood Khar", "Zainab Khar"], ["Muzaffargarh", "DG Khan", "Rajanpur"])),
    },
    {
      name: "Khurram Nawaz Gandapur",
      cnicPartial: "22405-XXXXX-1",
      position: "MNA - National Assembly",
      party: "PTI",
      province: "KPK",
      constituency: "NA-38 Dera Ismail Khan",
      riskScore: 35.6,
      riskTrend: "falling",
      flagCount: 3,
      assetsDeclared: "PKR 48 Million",
      lastUpdated: "2024-01-15",
      companiesJson: JSON.stringify([]),
      contractsJson: JSON.stringify([]),
      relativesJson: JSON.stringify([
        { name: "Ali Khan Gandapur (Brother)", relationship: "Sibling", companies: ["DI Khan Traders"], contracts: 1 },
      ]),
      fundingJson: JSON.stringify([
        { district: "Dera Ismail Khan", amount: "PKR 780M", year: 2023, contractsBack: 1, suspiciousLinks: false },
      ]),
      riskFactorsJson: JSON.stringify([
        { factor: "Brother has minor contract in constituency", weight: 12.3, description: "Brother's small trading company received one supply contract", evidenceLevel: "low" },
        { factor: "Asset declaration - minor gaps", weight: 13.3, description: "Some agricultural land not clearly categorized", evidenceLevel: "low" },
        { factor: "Family political network", weight: 10.0, description: "Multiple family members in different levels of government without clear independence", evidenceLevel: "low" },
      ]),
      connectionsJson: JSON.stringify(buildConnections("Khurram Nawaz Gandapur", 8, [], ["Ali Khan Gandapur"], ["Dera Ismail Khan"])),
    },
  ];

  const insertedOfficials = await db.insert(officialsTable).values(officials).returning();
  console.log(`Inserted ${insertedOfficials.length} officials`);

  const alerts = [
    {
      title: "Ghost Employee Network Detected - AGPR Punjab Payroll",
      description: "Cross-referencing NADRA CNIC status with AGPR federal payroll reveals 47 employees drawing salaries with deceased CNIC status. Concentrated in 3 departments with connections to NA-208 constituency.",
      severity: "critical",
      status: "new",
      officialId: insertedOfficials[6].id,
      officialName: "Ghulam Mustafa Khar",
      detectedAt: "2024-02-18T09:23:00Z",
      patternType: "ghost_employee",
      estimatedValue: "PKR 2.8M/month",
      dataSourcesJson: JSON.stringify(["NADRA", "AGPR", "ECP"]),
    },
    {
      title: "Circular Contract Pattern - Hussain Steel Mills & Sialkot Bypass",
      description: "MNA Malik Asghar Hussain directed PKR 3.4B in PSDP funds to Sialkot district. 7 contracts traced back to Hussain Steel Mills (directly owned) and Al-Hussain Construction (wife is director). Pattern matches fund→family→contract cycle.",
      severity: "critical",
      status: "reviewing",
      officialId: insertedOfficials[0].id,
      officialName: "Malik Asghar Hussain",
      detectedAt: "2024-02-15T14:11:00Z",
      patternType: "circular_contract",
      estimatedValue: "PKR 1.54B",
      dataSourcesJson: JSON.stringify(["PPRA", "SECP", "PSDP", "ECP"]),
    },
    {
      title: "Asset Enrichment Anomaly - Khar Family Petroleum Expansion",
      description: "Khar Petroleum Ltd assets grew 340% in 2 years during period of MPA Khar's budget committee membership. NHA motorway service area contracts worth PKR 2.1B awarded without evidence of competitive tender.",
      severity: "critical",
      status: "new",
      officialId: insertedOfficials[6].id,
      officialName: "Ghulam Mustafa Khar",
      detectedAt: "2024-02-17T11:45:00Z",
      patternType: "relative_enrichment",
      estimatedValue: "PKR 2.1B",
      dataSourcesJson: JSON.stringify(["SECP", "PPRA", "FBR", "ECP"]),
    },
    {
      title: "Fund Diversion Signal - Hyderabad Drainage Project",
      description: "Sindh PPRA contract for Hyderabad Drainage worth PKR 890M shows 34% cost inflation vs. comparable 2021 project. Vendor Indus Trade International registered only 18 months before winning contract, with MPA Rubina Akhtar's brother-in-law as director.",
      severity: "high",
      status: "new",
      officialId: insertedOfficials[1].id,
      officialName: "Bibi Rubina Akhtar",
      detectedAt: "2024-02-14T16:30:00Z",
      patternType: "fund_diversion",
      estimatedValue: "PKR 305M (inflated portion)",
      dataSourcesJson: JSON.stringify(["SPPRA", "SECP", "ECP"]),
    },
    {
      title: "Procurement Anomaly - KPK Ring Road Single Bidder",
      description: "KPK Construction Consortium won NA-19 ring road contract with only one other bidder (disqualified on day of opening). Company registered 58 days before tender publication. Son Bilal Qureshi is sole director.",
      severity: "high",
      status: "reviewing",
      officialId: insertedOfficials[2].id,
      officialName: "Fazal ur Rahman Qureshi",
      detectedAt: "2024-02-10T10:15:00Z",
      patternType: "procurement_anomaly",
      estimatedValue: "PKR 412M",
      dataSourcesJson: JSON.stringify(["KPPRA", "SECP", "NADRA"]),
    },
    {
      title: "Senator Sugar Policy Conflict of Interest",
      description: "Senator Chaudhry Nawaz Baig voted in favor of sugar export quota increase on 3 occasions while simultaneously serving as Chairman of Baig Sugar Mills Ltd (1.2M ton/year capacity). ECP declaration lists sugar mills but no conflict of interest declaration filed.",
      severity: "high",
      status: "new",
      officialId: insertedOfficials[3].id,
      officialName: "Chaudhry Nawaz Baig",
      detectedAt: "2024-02-08T08:00:00Z",
      patternType: "asset_mismatch",
      estimatedValue: "Policy impact: PKR 8B+ sugar sector",
      dataSourcesJson: JSON.stringify(["ECP", "SECP", "Senate Records", "PPRA"]),
    },
    {
      title: "Undisclosed Land Holdings - Multiple Provinces",
      description: "Punjab Zameen and PRAL land records cross-referenced with ECP declarations reveal 8 properties across Punjab and Sindh owned by Khar family members not disclosed in official asset declarations.",
      severity: "high",
      status: "new",
      officialId: insertedOfficials[6].id,
      officialName: "Ghulam Mustafa Khar",
      detectedAt: "2024-02-16T13:20:00Z",
      patternType: "asset_mismatch",
      estimatedValue: "PKR 340M (estimated market value)",
      dataSourcesJson: JSON.stringify(["PRAL", "ECP", "TMA", "NADRA"]),
    },
    {
      title: "Ghost School Construction Payroll - PS-52 Rural Scheme",
      description: "AGPR payroll for Bibi Rubina Akhtar constituency school construction shows 23 laborers on payroll including 4 CNICs matching deceased individuals in NADRA database. Total fraudulent payroll estimated at PKR 1.4M/month over 8-month project.",
      severity: "medium",
      status: "reviewing",
      officialId: insertedOfficials[1].id,
      officialName: "Bibi Rubina Akhtar",
      detectedAt: "2024-01-22T12:00:00Z",
      patternType: "ghost_employee",
      estimatedValue: "PKR 11.2M",
      dataSourcesJson: JSON.stringify(["NADRA", "AGPR", "SPPRA"]),
    },
    {
      title: "Minor Health Contract Conflict - Waqar Medical Centre",
      description: "Dr. Saima Waqar's husband co-owns Waqar Medical Centre which received PKR 23M Sindh government free medical camp contract. Low risk due to small size, disclosed ownership, and single occurrence.",
      severity: "low",
      status: "resolved",
      officialId: insertedOfficials[5].id,
      officialName: "Dr. Saima Waqar",
      detectedAt: "2024-01-10T09:00:00Z",
      patternType: "circular_contract",
      estimatedValue: "PKR 23M",
      dataSourcesJson: JSON.stringify(["SPPRA", "SECP", "ECP"]),
    },
    {
      title: "Federal Payroll Anomaly - Ministry of Housing 2023 Batch",
      description: "Cross-referencing AGPR Ministry of Housing payroll with NADRA CNIC verification found 34 employees with CNIC status anomalies (deceased, duplicate, or invalid). Monthly payout: PKR 4.1M. No connection to specific elected official confirmed yet.",
      severity: "critical",
      status: "new",
      officialId: null,
      officialName: null,
      detectedAt: "2024-02-19T07:30:00Z",
      patternType: "ghost_employee",
      estimatedValue: "PKR 49.2M/year",
      dataSourcesJson: JSON.stringify(["AGPR", "NADRA", "FBR"]),
    },
  ];

  const insertedAlerts = await db.insert(alertsTable).values(alerts).returning();
  console.log(`Inserted ${insertedAlerts.length} alerts`);
  console.log("Seeding complete!");
}

seed().catch(console.error);
